export const keymaps_win: string[][] = [
["MIDI","[Alt+L]","Show/Hide Controller Lanes"],
["MIDI","[Q]","Quantize"],
["Editors","[Ctrl+I]","Show/Hide Infoview"],
["Editors","[Alt+O]","Show/Hide Overview"],
["Edit","[Ctrl+Shift+I]","Edit Inplace"],
["Edit","[Ctrl+R]","Open Score Editor"],
["Edit","[Return]","Open/Close Editor"],
["Edit","[Ctrl+Z]","Undo"],
["Edit","[Ctrl+Shift+Z]","Redo"],
["Edit","[Ctrl+X]","Cut"],
["Edit","[Ctrl+C]","Copy"],
["Edit","[Ctrl+V]","Paste"],
["Edit","[Ctrl+A]","Select All"],
["Edit","[Ctrl+Shift+A]","Select None"],
["Edit","[Ctrl+D]","Duplicate"],
["Edit","[Ctrl+E]","Open"],
["Edit","[Ctrl+K]","Repeat"],
["Edit","[U]","Move to Front"],
["Edit","[Ctrl+Shift+L]","Lock"],
["Edit","[Ctrl+Shift+U]","Unlock"],
["Edit","[Ctrl+Shift+X]","Cut Time"],
["Edit","[Shift+Backspace]","Delete Time"],
["Edit","[Ctrl+Shift+V]","Paste Time"],
["Edit","[Alt+V]","Paste at Origin"],
["Edit","[Shift+V]","Paste Relative to Cursor"],
["Edit","[Shift+X]","Split Range"],
["Edit","[Ctrl+Shift+E]","Insert Silence"],
["Edit","[Ctrl+Alt+I]","Invert Selection"],
["Edit","[Alt+X]","Split at Cursor"],
["Edit","[Ctrl+L]","Move to Cursor"],
["Edit","[Ctrl+G]","Group"],
["Edit","[Ctrl+U]","Ungroup"],
["Edit","[S]","Solo"],
["Edit","[M]","Mute"],
["Edit","[R]","Record Enable"],
["Edit","[W]","Write"],
["Edit","[Ctrl+Shift+Up Arrow]","Primary Parameter: Increase"],
["Edit","[Ctrl+Shift+Down Arrow]","Primary Parameter: Decrease"],
["Edit","[Ctrl+Shift+Right Arrow]","Secondary Parameter: Increase"],
["Edit","[Ctrl+Shift+Left Arrow]","Secondary Parameter: Decrease"],
["Edit","[Shift+M]","Mute Events"],
["Edit","[Shift+U]","Unmute Events"],
["Edit","[Alt+M]","Mute/Unmute Objects"],
["Edit","[Ctrl+F]","Find Track/Channel"],
["Edit","[K]","Toggle Group Tracks"],
["Edit","[E]","Left Selection Side to Cursor"],
["Edit","[D]","Right Selection Side to Cursor"],
["Edit","[Alt+C]","Stationary Cursor"],
["Edit","[F]","Autoscroll"],
["Edit","[J]","Snap On/Off"],
["Edit","[Alt+E]","Expand/Reduce"],
["Edit","[Alt+A]","Activate/Deactivate"],
["Edit","[Alt+F]","Flip/Invert"],
["Set Insert Length","[Alt+,]","T"],
["Set Insert Length","[Alt+.]","."],
["Set Insert Length","[Alt+1]","1"],
["Set Insert Length","[Alt+2]","2"],
["Set Insert Length","[Alt+3]","4"],
["Set Insert Length","[Alt+4]","8"],
["Set Insert Length","[Alt+5]","16"],
["Set Insert Length","[Alt+6]","32"],
["Set Insert Length","[Alt+7]","64"],
["Set Insert Length","[Alt+8]","128"],
["Devices","[Alt+K]","Virtual Keyboard"],
["Devices","[F3]","Mixer"],
["Devices","[Alt+F3]","MixConsole Lower Zone"],
["Devices","[F12]","VST Performance"],
["Devices","[F4]","VST Connections"],
["Devices","[F8]","Video"],
["Devices","[F11]","VST Instruments"],
["Media","[Shift+Enter]","Preview Start"],
["Media","[Shift+Pad0]","Preview Stop"],
["Media","[Shift+Pad /]","Preview Cycle On/Off"],
["Media","[F5]","Open MediaBay"],
["Media","[Shift+F5]","Search MediaBay"],
["Media","[Ctrl+Alt+Pad6]","Open/Close Attribute Inspector"],
["Media","[Ctrl+Alt+Pad4]","Open/Close File Browser"],
["Media","[Ctrl+Alt+Pad2]","Open/Close Previewer"],
["Media","[Ctrl+Alt+Pad5]","Open/Close Filters"],
["Media","[Ctrl+Alt+Pad8]","Open/Close Favorites"],
["File","[Ctrl+N]","New"],
["File","[Ctrl+O]","Open"],
["File","[Ctrl+W]","Close"],
["File","[Ctrl+S]","Save"],
["File","[Ctrl+Alt+S]","Save New Version"],
["File","[Ctrl+Shift+S]","Save As"],
["File","[Ctrl+Q]","Quit"],
["Navigate","[Left Arrow]","Left"],
["Navigate","[Right Arrow]","Right"],
["Navigate","[Up Arrow]","Up"],
["Navigate","[Down Arrow]","Down"],
["Navigate","[Shift+Left Arrow]","Add Left"],
["Navigate","[Shift+Right Arrow]","Add Right"],
["Navigate","[Shift+Up Arrow]","Add Up"],
["Navigate","[Shift+Down Arrow]","Add Down"],
["Navigate","[Home]","Top"],
["Navigate","[End]","Bottom"],
["Navigate","[Ctrl+Space]","Toggle Selection"],
["Zoom","[Alt+S]","Zoom to Selection"],
["Zoom","[Shift+E]","Zoom to Event"],
["Zoom","[Shift+F]","Zoom Full"],
["Zoom","[Shift+H]","Zoom In Vertically"],
["Zoom","[Shift+G]","Zoom Out Vertically"],
["Zoom","[Alt+H]","Zoom In On Waveform Vertically"],
["Zoom","[Alt+G]","Zoom Out Of Waveform Vertically"],
["Zoom","[Ctrl+Down Arrow]","Zoom In Tracks"],
["Zoom","[Ctrl+Up Arrow]","Zoom Out Tracks"],
["Zoom","[Z]","Zoom Tracks Exclusive"],
["Zoom","[H]","Zoom In"],
["Zoom","[G]","Zoom Out"],
["Project","[Shift+Del]","Remove Selected Tracks"],
["Project","[Ctrl+P]","Open Pool"],
["Project","[Ctrl+M]","Open Markers"],
["Project","[Ctrl+T]","Open Tempo Track"],
["Project","[Alt+Shift+S]","Colors"],
["Project","[Shift+S]","Setup"],
["Project","[Alt+Shift+C]","Set Track/Event Color"],
["Project","[Ctrl+B]","Open Browser"],
["AddTrack","[T]","OpenDialog"],
["Window Zones","[Ctrl+Alt+R]","Show/Hide Right Zone"],
["Window Zones","[Ctrl+Alt+U]","Show/Hide Upper Zone"],
["Window Zones","[Ctrl+Alt+T]","Show/Hide Transport Zone"],
["Window Zones","[Ctrl+Alt+Left Arrow]","Show Previous Tab"],
["Window Zones","[Ctrl+Alt+Right Arrow]","Show Next Tab"],
["Audio","[X]","Crossfade"],
["Audio","[Shift+Q]","Auto-Grid"],
["Audio","[A]","Adjust Fades to Range"],
["Direct Offline Processing","[F7]","Direct Offline Processing"],
["Transport","[F2]","Panel"],
["Transport","[Alt+Space]","Play Selection Range"],
["Transport","[N]","Locate Next Event"],
["Transport","[B]","Locate Previous Event"],
["Transport","[Alt+N]","Locate Next Hitpoint"],
["Transport","[Alt+B]","Locate Previous Hitpoint"],
["Transport","[P]","Locators to Selection"],
["Transport","[Enter]","Start"],
["Transport","[Pad0]","Stop"],
["Transport","[Space]","StartStop"],
["Transport","[Pad *]","Record"],
["Transport","[Shift+Pad *]","Global Retrospective Record"],
["Transport","[Pad -]","Rewind"],
["Transport","[Pad +]","Forward"],
["Transport","[Shift+Pad -]","Fast Rewind"],
["Transport","[Shift+Pad +]","Fast Forward"],
["Transport","[Pad /]","Cycle"],
["Transport","[I]","Auto Punch In"],
["Transport","[O]","Auto Punch Out"],
["Transport","[Ctrl+Pad +]","Nudge Cursor Right"],
["Transport","[Ctrl+Pad -]","Nudge Cursor Left"],
["Transport","[Pad1]","To Left Locator"],
["Transport","[Pad2]","To Right Locator"],
["Transport","[Shift+1]","To Marker 1"],
["Transport","[Shift+2]","To Marker 2"],
["Transport","[Shift+Pad1]","Recall Cycle Marker 1"],
["Transport","[Shift+Pad2]","Recall Cycle Marker 2"],
["Transport","[Shift+Pad3]","Recall Cycle Marker 3"],
["Transport","[Shift+Pad4]","Recall Cycle Marker 4"],
["Transport","[Shift+Pad5]","Recall Cycle Marker 5"],
["Transport","[Shift+Pad6]","Recall Cycle Marker 6"],
["Transport","[Shift+Pad7]","Recall Cycle Marker 7"],
["Transport","[Shift+Pad8]","Recall Cycle Marker 8"],
["Transport","[Shift+Pad9]","Recall Cycle Marker 9"],
["Transport","[Ctrl+Pad1]","Set Left Locator"],
["Transport","[Ctrl+Pad2]","Set Right Locator"],
["Transport","[Ctrl+1]","Set Marker 1"],
["Transport","[Ctrl+2]","Set Marker 2"],
["Transport","[Shift+N]","Locate Next Marker"],
["Transport","[Shift+B]","Locate Previous Marker"],
["Transport","[Insert]","Insert Marker"],
["Transport","[Shift+P]","Input Position"],
["Transport","[Shift+L]","Input Left Locator"],
["Transport","[Shift+R]","Input Right Locator"],
["Transport","[Shift+D]","Input Locator Duration"],
["Transport","[Shift+I]","Input Punch In Position"],
["Transport","[Shift+O]","Input Punch Out Position"],
["Transport","[Shift+T]","Input Tempo"],
["Transport","[Shift+C]","Input Time Signature"],
["Transport","[C]","Metronome On"],
["Transport","[Alt+Shift+T]","Use External Sync"],
["Transport","[.]","Exchange Time Formats"],
["Transport","[L]","Locate Selection"],
["Transport","[Alt+P]","Loop Selection"],
["Tool","[F10]","Next Tool"],
["Tool","[F9]","Previous Tool"],
["Tool","[1]","Select Tool"],
["Tool","[2]","Range Tool"],
["Tool","[3]","Split Tool"],
["Tool","[4]","Glue Tool"],
["Tool","[5]","Delete Tool"],
["Tool","[6]","Zoom Tool"],
["Tool","[7]","Mute Tool"],
["Tool","[8]","Draw Tool"],
["Tool","[9]","Play Tool"],
["Tool","[0]","Drumstick Tool"],
["Tool","[Alt+Shift+1]","Combine Selection Tools On/Off"],
["Automation","[Alt+R]","Toggle Read Enable All Tracks"],
["Automation","[Alt+W]","Toggle Write Enable All Tracks"],
["Automation","[F6]","Open Panel"],
["Chords","[Ctrl+Shift+C]","ChordPad"],
["TrackVersions","[Ctrl+Shift+N]","New Version"],
["TrackVersions","[Ctrl+Shift+D]","Duplicate Version"],
["TrackVersions","[Ctrl+Shift+H]","Next Version"],
["TrackVersions","[Ctrl+Shift+G]","Previous Version"],
["MixConsole History","[Alt+Z]","Undo MixConsole Step"],
["MixConsole History","[Alt+Shift+Z]","Redo MixConsole Step"],
["Nudge","[Alt+Left Arrow]","Start Left"],
["Nudge","[Alt+Shift+Right Arrow]","Start Right"],
["Nudge","[Alt+Shift+Left Arrow]","End Left"],
["Nudge","[Alt+Right Arrow]","End Right"],
["Nudge","[Alt+Up Arrow]","Top Up"],
["Nudge","[Alt+Shift+Down Arrow]","Top Down"],
["Nudge","[Alt+Shift+Up Arrow]","Bottom Up"],
["Nudge","[Alt+Down Arrow]","Bottom Down"],
["Nudge","[Ctrl+Left Arrow]","Left"],
["Nudge","[Ctrl+Right Arrow]","Right"],
["Workspaces","[Ctrl+Pad0]","New"],
["Workspaces","[Alt+U]","Update Workspace"],
["Workspaces","[Alt+Pad0]","No Workspace"],
["Workspaces","[Alt+Pad1]","Workspace 1"],
["Workspaces","[Alt+Pad2]","Workspace 2"],
["Workspaces","[Alt+Pad3]","Workspace 3"],
["Workspaces","[Alt+Pad4]","Workspace 4"],
["Workspaces","[Alt+Pad5]","Workspace 5"],
["Workspaces","[Alt+Pad6]","Workspace 6"],
["Workspaces","[Alt+Pad7]","Workspace 7"],
["Workspaces","[Alt+Pad8]","Workspace 8"],
["Workspaces","[Alt+Pad9]","Workspace 9"],
["Workspaces","[Ctrl+Alt+Pad0]","Workspace X"],
]
